### ISSUE TITLE
communication with agent failed

### ISSUE THREAD

**Issue by inos-github** [aeolwyr/tergent#6]
I am trying to use your tool on an xiaomi mi8 with MIUI 10.01 but without success. 

Termux v. 0.75
Termux api v. 0.37
tergent v. 0.1.1-1 aarch64 (release) 

Here is the log:

➜   termux-keystore list
[                                               {
    "alias": "martin@mia",
    "algorithm": "RSA",
    "size": 2048,
    "inside_secure_hardware": true,
    "user_authentication": {
      "required": false,
      "enforced_by_secure_hardware": false
    }
  },
  {
    "alias": "TermuxFingerprintAPIKey"
  }
]
➜  eval $(tergent)
Agent pid 21139                               
➜  ssh-add -l
thread '<unnamed>' panicked at 'Cannot read one of the keys.', libcore/option.rs:989:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error fetching identities: communication with agent failed

**Comment by aeolwyr** [comment]
I see that the key named `TermuxFingerprintAPIKey` was causing a fatal error here.

[Release 1.0](https://github.com/aeolwyr/tergent/releases/tag/1.0.0) should skip these keys instead of breaking. Please note that if you wish to upgrade, you will need to follow the README as you'll need to generate new keys. Let me know if this fixes the issue!

**Comment by inos-github** [comment]
Your new release fixed the issue, thanks!

**Comment by aeolwyr** [comment]
No problem, thanks for the update.
